server:
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/tank_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false
      username: root
      password: 123456
      validation-query: SELECT 1
springfox:
  documentation:
    auto-startup: true
    enabled: true
logging:
  level:
    com.github.w4o: debug

tank:
  jwt:
    secret: xxxx
    expire: 7200
